### ISSUE TITLE
Cannot install on Windows 10 x64 and Node.js 6.11.2

### ISSUE THREAD

**Issue by vsdigitall** [danieloneill/nodeacr122u#3]
**Hello, when I run 'npm install nodeacr122u' I receve following error:**

147 silly install printInstalled
148 verbose stack Error: nodeacr122u@1.0.0 install: `(node-gyp rebuild 2> builderror.log) || (exit 1)`
148 verbose stack Exit status 1
148 verbose stack     at EventEmitter.<anonymous> (C:\job\node\node_modules\npm\lib\utils\lifecycle.js:255:16)
148 verbose stack     at emitTwo (events.js:106:13)
148 verbose stack     at EventEmitter.emit (events.js:191:7)
148 verbose stack     at ChildProcess.<anonymous> (C:\job\node\node_modules\npm\lib\utils\spawn.js:40:14)
148 verbose stack     at emitTwo (events.js:106:13)
148 verbose stack     at ChildProcess.emit (events.js:191:7)
148 verbose stack     at maybeClose (internal/child_process.js:891:16)
148 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
149 verbose pkgid nodeacr122u@1.0.0
150 verbose cwd C:\job\node
151 error Windows_NT 10.0.15063
152 error argv "C:\\job\\node\\node.exe" "C:\\job\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodeacr122u"
153 error node v6.11.2
154 error npm  v3.10.10
155 error code ELIFECYCLE
156 error nodeacr122u@1.0.0 install: `(node-gyp rebuild 2> builderror.log) || (exit 1)`
156 error Exit status 1
157 error Failed at the nodeacr122u@1.0.0 install script '(node-gyp rebuild 2> builderror.log) || (exit 1)'.
157 error Make sure you have the latest version of node.js and npm installed.
157 error If you do, this is most likely a problem with the nodeacr122u package,
157 error not with npm itself.
157 error Tell the author that this fails on your system:
157 error     (node-gyp rebuild 2> builderror.log) || (exit 1)
157 error You can get information on how to open an issue for this project with:
157 error     npm bugs nodeacr122u
157 error Or if that isn't available, you can get their info via:
157 error     npm owner ls nodeacr122u
157 error There is likely additional logging output above.
158 verbose exit [ 1, true ]

**Can you please tell me how can I install your module?**

**Comment by danieloneill** [comment]
I'm sorry, I don't think it's possible. This module depends on libusb which
as far as I'm aware doesn't exist on Windows, only Linux, Unix, Mac, etc.
